MLK-22094 usb: cdns3: include head directory to find it
commit  from
https://source.codeaurora.org/external/imx/linux-imx

define_trace.h needs to know how to find our header, otherwise
we will have below build error:

In file included from drivers/usb/cdns3/trace.h:446:0,
                 from drivers/usb/cdns3/trace.c:11:
./include/trace/define_trace.h:89:43: fatal error: ./trace.h: No such
file or directory
 #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
                                           ^
compilation terminated.
scripts/Makefile.build:326: recipe for target
'drivers/usb/cdns3/trace.o' failed
make[3]: *** [drivers/usb/cdns3/trace.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      drivers/usb/host/pci-quirks.o
  CC      drivers/usb/isp1760/isp1760-core.o
  CC      drivers/usb/misc/ehset.o
  CC      drivers/usb/isp1760/isp1760-if.o
scripts/Makefile.build:585: recipe for target 'drivers/usb/cdns3' failed
make[2]: *** [drivers/usb/cdns3] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC      drivers/usb/misc/usb3503.o
  CC      drivers/usb/host/ehci-hcd.o
  CC      drivers/usb/isp1760/isp1760-hcd.o

Acked-by: Peter Chen <peter.chen@nxp.com>
Signed-off-by: Li Jun <jun.li@nxp.com>
(cherry picked from commit b0067d4b7c4e6f11625d3989b903189d73a45363)
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>