net: core: Fix undeclared error for devnet_rename_seq
Starting with commit 29d1d0c72464 ("net: core: device_rename:
Use rwsem instead of a seqcount") devnet_rename_seq was
replaced with devnet_rename_sem.

This piece of code was left by mistake after a -rt merge and
causes the following error:

net/core/dev.c:1263:28: error: 'devnet_rename_seq' undeclared
(first use in this function); did you mean 'devnet_rename_sem'?
|  1263 |  __raw_write_seqcount_end(&devnet_rename_seq);
|       |                            ^~~~~~~~~~~~~~~~~

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>