MLK-21985-4 ASoC: imx-cs42888: fix build for next 20190607 upgrade
commit  from
https://source.codeaurora.org/external/imx/linux-imx

API change due to:
adb76b5b9c47 ("ASoC: soc-core: remove legacy style dai_link")

Caused below error:
../sound/soc/fsl/imx-cs42888.c:272:3: error: unknown field ‘codec_dai_name’ specified in initializer
   .codec_dai_name = "cs42888",
   ^
../sound/soc/fsl/imx-cs42888.c:272:3: warning: initialization from incompatible pointer type
../sound/soc/fsl/imx-cs42888.c:272:3: warning: (near initialization for ‘imx_cs42888_dai[0].cpus’)
../sound/soc/fsl/imx-cs42888.c:279:3: error: unknown field ‘codec_name’ specified in initializer
   .codec_name = "snd-soc-dummy",
   ^
../sound/soc/fsl/imx-cs42888.c:279:3: warning: initialization from incompatible pointer type
../sound/soc/fsl/imx-cs42888.c:279:3: warning: (near initialization for ‘imx_cs42888_dai[1].cpus’)
../sound/soc/fsl/imx-cs42888.c:280:3: error: unknown field ‘codec_dai_name’ specified in initializer
   .codec_dai_name = "snd-soc-dummy-dai",
   ^
../sound/soc/fsl/imx-cs42888.c:280:3: warning: initialization makes integer from pointer without a cast
../sound/soc/fsl/imx-cs42888.c:280:3: warning: (near initialization for ‘imx_cs42888_dai[1].num_cpus’)
../sound/soc/fsl/imx-cs42888.c:280:3: error: initializer element is not computable at load time
../sound/soc/fsl/imx-cs42888.c:280:3: error: (near initialization for ‘imx_cs42888_dai[1].num_cpus’)
../sound/soc/fsl/imx-cs42888.c:290:3: error: unknown field ‘codec_dai_name’ specified in initializer
   .codec_dai_name = "cs42888",
   ^
../sound/soc/fsl/imx-cs42888.c:290:3: warning: initialization from incompatible pointer type
../sound/soc/fsl/imx-cs42888.c:290:3: warning: (near initialization for ‘imx_cs42888_dai[2].cpus’)
../sound/soc/fsl/imx-cs42888.c:291:3: error: unknown field ‘platform_name’ specified in initializer
   .platform_name = "snd-soc-dummy",

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>