net: dpaa: fix build failure due to skb_frag_t struct change
commit  from
https://source.codeaurora.org/external/imx/linux-imx

We met below build break due to new kernel change:
8842d285bafa ("net: Convert skb_frag_t to bio_vec")

../drivers/net/ethernet/freescale/dpaa/dpaa_eth.c: In function ‘dpaa_errata_a010022_has_dma_issue’:
../drivers/net/ethernet/freescale/dpaa/dpaa_eth.c:2137:37: error: ‘skb_frag_t’ has no member named ‘page_offset’
   if (CROSS_4K_BOUND((uintptr_t)frag->page_offset, frag->bv_len))
                                     ^
../drivers/net/ethernet/freescale/dpaa/dpaa_eth.c:2105:5: note: in definition of macro ‘CROSS_4K_BOUND’
  (((start) + (size)) > (((start) + 0x1000) & ~0xFFF))
     ^
../drivers/net/ethernet/freescale/dpaa/dpaa_eth.c:2137:37: error: ‘skb_frag_t’ has no member named ‘page_offset’
   if (CROSS_4K_BOUND((uintptr_t)frag->page_offset, frag->bv_len))
                                     ^
../drivers/net/ethernet/freescale/dpaa/dpaa_eth.c:2105:27: note: in definition of macro ‘CROSS_4K_BOUND’
  (((start) + (size)) > (((start) + 0x1000) & ~0xFFF))

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>