MLK-21985-9 Revert "MLK-20136-03 driver: soc: imx: add 100mts support for imx8mq low bus mode"
commit  from
https://source.codeaurora.org/external/imx/linux-imx

This reverts commit 7560cff21b7b92127675d5e955874af2827a9bca.

drivers/soc/imx/busfreq-imx8mq.o: In function `reduce_bus_freq':
/home/b29396/Work/linux/dash-linux-devel/build_v8/../drivers/soc/imx/busfreq-imx8mq.c:193: undefined reference to `imx_get_soc_revision'
/home/b29396/Work/linux/dash-linux-devel/build_v8/../drivers/soc/imx/busfreq-imx8mq.c:120: undefined reference to `imx_get_soc_revision'
drivers/soc/imx/busfreq-imx8mq.o: In function `set_high_bus_freq':
/home/b29396/Work/linux/dash-linux-devel/build_v8/../drivers/soc/imx/busfreq-imx8mq.c:327: undefined reference to `imx_get_soc_revision'
/home/b29396/Work/linux/dash-linux-devel/Makefile:1052: recipe for target 'vmlinux' failed
make[1]: *** [vmlinux] Error 1

upstream kernel did not export imx_get_soc_revision for mx8.
Need find a better way to support for both mx8m and mx8.

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>