net: Fix redefinition of dev_recursion_level
This error was introduced in commit e6f1979ced24 ("Merge branch
'v4.19/standard/base' into v4.19/standard/preempt-rt/base").

include/linux/netdevice.h:3066:19: error: redefinition of 'dev_recursion_level'
|  3066 | static inline int dev_recursion_level(void)
|       |                   ^~~~~~~~~~~~~~~~~~~
include/linux/netdevice.h:2641:19: note: previous definition of 'dev_recursion_level' was here
|  2641 | static inline int dev_recursion_level(void)
|       |                   ^~~~~~~~~~~~~~~~~~~
include/linux/netdevice.h:3071: warning: "XMIT_RECURSION_LIMIT" redefined
|  3071 | #define XMIT_RECURSION_LIMIT
include/linux/netdevice.h:2639: note: this is the location of the previous definition
|  2639 | #define XMIT_RECURSION_LIMIT 10

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>