MLK-19442-1 usb: host: xhci: export xhci_bus_suspend
commit  from
https://source.codeaurora.org/external/imx/linux-imx

It may be used by xhci platform driver, fixed below error when
building xhci as module.

ERROR: "xhci_bus_suspend" [drivers/usb/cdns3/cdns3.ko] undefined!
linux-imx/scripts/Makefile.modpost:92: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
linux-imx/Makefile:1231: recipe for target 'modules' failed
make[1]: *** [modules] Error 2

Reported-by: Bruce Zhang <bo.zhang@nxp.com>
Signed-off-by: Peter Chen <peter.chen@nxp.com>
(cherry picked from commit f4211724d6228a0515d93a320f1016947bd0c37c)
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>