overlays: Delete spi0-hw-cs
commit  57905943666757ba6e6a25aaa898d99e9845493d from
https://github.com/raspberrypi/linux.git rpi-5.4.y

The spi0-hw-cs overlay is unnecessary (and actually harmful) with the
current kernels. Delete it, leaving a note in the README and a
deprecation message from the firmware:

    dterror: overlay 'spi0-hw-cs' is deprecated: no longer necessary

Signed-off-by: Phil Elwell <phil@raspberrypi.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>