ASoC: codecs: fsl_mqs: fix build for 5.1 RC kernel
commit  from
https://source.codeaurora.org/external/imx/linux-imx

Due to below patch:
999f7f5af8eb ("ASoC: remove Codec related code")
codec related structures have been removed.
Need update legacy drivers accordingly.

  CC      sound/soc/codecs/hdmi-codec.o
  CC      sound/soc/codecs/si476x.o
../sound/soc/codecs/fsl_mqs.c: In function 'fsl_mqs_hw_params':
../sound/soc/codecs/fsl_mqs.c:65:35: error: 'struct snd_soc_dai' has no member named 'codec'
  struct snd_soc_codec *codec = dai->codec;
                                   ^
../sound/soc/codecs/fsl_mqs.c:66:9: error: implicit declaration of function 'snd_soc_codec_get_drvdata' [-Werror=implicit-function-declaration]
  struct fsl_mqs *mqs_priv = snd_soc_codec_get_drvdata(codec);
         ^
../sound/soc/codecs/fsl_mqs.c:66:29: warning: initialization makes pointer from integer without a cast
  struct fsl_mqs *mqs_priv = snd_soc_codec_get_drvdata(codec);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>