usb: dwc3: gadget: declare __dwc3_gadget_kick_transfer as global
Since the function "__dwc3_gadget_kick_transfer" is used by
drivers/usb/dwc3/gadget_hibernation.c, so declare it as global.
This is to fix a compile error as below:

drivers/usb/dwc3/gadget.c:1248:12: error: static declaration of '__dwc3_gadget_kick_transfer' follows non-static declaration
 1248 | static int __dwc3_gadget_kick_transfer(struct dwc3_ep *dep)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from drivers/usb/dwc3/gadget.c:27:
drivers/usb/dwc3/gadget.h:126:5: note: previous declaration of '__dwc3_gadget_kick_transfer' was here
  126 | int __dwc3_gadget_kick_transfer(struct dwc3_ep *dep);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>