printk: Fix build failures caused by v5.4.22 merge
A hunk of code that was already removed from RT upstream was introduced by
the merger of v5.4.22 and cause the following build failures. Remove it.

kernel/printk/printk.c: In function 'register_console':
kernel/printk/printk.c:2530:3: error: implicit declaration of function 'logbuf_lock_irqsave'; did you mean 'xa_lock_irqsave'? [-Werror=implicit-function-declaration]
 2530 |   logbuf_lock_irqsave(flags);
      |   ^~~~~~~~~~~~~~~~~~~
      |   xa_lock_irqsave
kernel/printk/printk.c:2530:23: error: 'flags' undeclared (first use in this function)
 2530 |   logbuf_lock_irqsave(flags);
      |                       ^~~~~
kernel/printk/printk.c:2530:23: note: each undeclared identifier is reported only once for each function it appears in
  CC      arch/x86/entry/syscall_32.o
kernel/printk/printk.c:2540:3: error: 'exclusive_console' undeclared (first use in this function)
 2540 |   exclusive_console = newcon;
      |   ^~~~~~~~~~~~~~~~~
kernel/printk/printk.c:2541:3: error: 'exclusive_console_stop_seq' undeclared (first use in this function)
 2541 |   exclusive_console_stop_seq = console_seq;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
kernel/printk/printk.c:2541:32: error: 'console_seq' undeclared (first use in this function); did you mean 'console_sem'?
 2541 |   exclusive_console_stop_seq = console_seq;
      |                                ^~~~~~~~~~~
      |                                console_sem
kernel/printk/printk.c:2543:3: error: 'console_idx' undeclared (first use in this function); did you mean 'console_sem'?
 2543 |   console_idx = syslog_idx;
      |   ^~~~~~~~~~~
      |   console_sem
kernel/printk/printk.c:2543:17: error: 'syslog_idx' undeclared (first use in this function); did you mean 'syslog_time'?
 2543 |   console_idx = syslog_idx;
      |                 ^~~~~~~~~~

Signed-off-by: He Zhe <zhe.he@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>