MLK-21985-5 ASoC: imx-wm8960: fix build for next 20190607 upgrade
commit  from
https://source.codeaurora.org/external/imx/linux-imx

API change due to:
adb76b5b9c47 ("ASoC: soc-core: remove legacy style dai_link")

../sound/soc/fsl/imx-wm8960.c:538:3: warning: statement with no effect [-Wunused-value]
   imx_wm8960_dai[0].codec_name     = "rpmsg-audio-codec-wm8960";
   ^
../sound/soc/fsl/imx-wm8960.c:539:20: error: ‘struct snd_soc_dai_link’ has no member named ‘codec_dai_name’
   imx_wm8960_dai[0].codec_dai_name = "rpmsg-wm8960-hifi";
                    ^
../sound/soc/fsl/imx-wm8960.c:539:3: warning: statement with no effect [-Wunused-value]
   imx_wm8960_dai[0].codec_dai_name = "rpmsg-wm8960-hifi";
   ^
../sound/soc/fsl/imx-wm8960.c:547:20: error: ‘struct snd_soc_dai_link’ has no member named ‘codec_of_node’
   imx_wm8960_dai[0].codec_of_node = codec_np;
                    ^
../sound/soc/fsl/imx-wm8960.c:547:3: warning: statement with no effect [-Wunused-value]
   imx_wm8960_dai[0].codec_of_node = codec_np;
   ^
../sound/soc/fsl/imx-wm8960.c:549:19: error: ‘struct snd_soc_dai_link’ has no member named ‘cpu_dai_name’
  imx_wm8960_dai[0].cpu_dai_name = dev_name(&cpu_pdev->dev);
                   ^
../sound/soc/fsl/imx-wm8960.c:549:2: warning: statement with no effect [-Wunused-value]
  imx_wm8960_dai[0].cpu_dai_name = dev_name(&cpu_pdev->dev);
  ^
../sound/soc/fsl/imx-wm8960.c:550:19: error: ‘struct snd_soc_dai_link’ has no member named ‘platform_of_node’
  imx_wm8960_dai[0].platform_of_node = cpu_np;
                   ^
../sound/soc/fsl/imx-wm8960.c:550:2: warning: statement with no effect [-Wunused-value]
  imx_wm8960_dai[0].platform_of_node = cpu_np;
  ^

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>