can: flexcan: fix wrong merging commit cd9f13c594613
This is to fix the below error build:

drivers/net/can/flexcan.c:1637:30: error: 'flexcan_irq' undeclared (first use in this function)
DEBUG:	1637 |  err = request_irq(dev->irq, flexcan_irq, IRQF_SHARED, dev->name, dev);
1637 |  err = request_irq(dev->irq, flexcan_irq, IRQF_SHARED, dev->name, dev);
DEBUG:	|                              ^~~~~~~~~~~
|                              ^~~~~~~~~~~

It is caused by wrong merging the upstream commit cd9f13c59461351d with this branch.
cd9f13c59461351d(can: flexcan: flexcan_chip_start(): fix erroneous flexcan_transceiver_enable() during bus-off recovery).
Now added the missing part for this patch.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>